version: "2"

build:
  os: "ubuntu-22.04"
  apt_packages: [openjdk-21-jdk]
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - theoretical-microservice-1/gradlew generateOpenApiDocs
  #commands: [theoretical-microservice-1/gradlew generateOpenApiDocs]

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
