name: api-test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy-test-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Deploy app
        run: |
          cd theoretical-microservice-1
          nohup ./gradlew bootRun &
          for attempt in {1..30}; do sleep 1; if curl http://localhost:8080/greeting -v --fail-with-body; then echo "App seems to be up"; break; fi; echo "waiting for app..."; done
      - name: Run tests
        run: |
          cd api-tests
          ./gradlew test

  run-tests-parallel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        executorId: [0, 1]
    steps:
      run: |
        cd api-tests
        ./gradlew test -DtotalNodes=2 -DexecutorId=${{ matrix.executorId }}
